components:
  schemas:
    BusinessActivityDto_External:
      properties:
        businessId:
          description: business id (Y-tunnus)
          maxLength: 10
          type: string
        businessType:
          description: business type, codeset TYÖNHAKUPROFIILI_TYÖN_TYYPPI
          type: string
        description:
          $ref: '#/components/schemas/DescriptionItem_External'
          description: description
        interval:
          $ref: '#/components/schemas/IntervalItem_External'
          description: interval
        name:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          maxLength: 3
          type: object
        title:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          maxLength: 3
          type: object
        useWithMatching:
          description: will be used in matching algorithms
          type: boolean
        visibleToEmployer:
          description: will be visible to potential employers
          type: boolean
      type: object
    CertificationDto_External:
      properties:
        cardCodes:
          description: 'cards and permissions, codeset: TYÖNHAKUPROFIILI_LUPA_KORTTI'
          items:
            type: string
          maxItems: 120
          maxLength: 120
          minItems: 0
          type: array
        description:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          maxLength: 3
          type: object
      type: object
    DescriptionItem_External:
      properties:
        description:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          maxLength: 3
          type: object
        occupations:
          description: Esco occupations
          items:
            $ref: '#/components/schemas/EscoEntity_External'
          maxItems: 120
          maxLength: 120
          minItems: 0
          type: array
        skills:
          description: Esco skills
          items:
            $ref: '#/components/schemas/EscoEntity_External'
          maxItems: 120
          maxLength: 120
          minItems: 0
          type: array
      type: object
    DrivingLicenseDto_External:
      properties:
        description:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          maxLength: 3
          type: object
        licenseClasses:
          description: 'driving license classes, codeset: AJOKORTTILUOKKA'
          items:
            type: string
          maxItems: 120
          maxLength: 120
          minItems: 0
          type: array
        ownCarAvailable:
          description: possibility to use your own car
          examples:
            - 'true'
          type: boolean
      type: object
    EducationDto_External:
      properties:
        customDegreeName:
          additionalProperties:
            type: string
          description: 'custom name of the degree - keys: languages (fi,sv,en), values:
            localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          maxLength: 3
          type: object
        degreeCode:
          description: 'degree code, codeset: TYÖNHAKUPROFIILI_KOULUTUS'
          type: string
        degreeInstitution:
          additionalProperties:
            type: string
          description: 'degree institution - keys: languages (fi,sv,en), values: localized
            descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          maxLength: 3
          type: object
        description:
          $ref: '#/components/schemas/DescriptionItem_External'
          description: description
        interval:
          $ref: '#/components/schemas/EducationIntervalItem_External'
          description: validity interval
        useWithMatching:
          description: will be used in matching algorithms
          type: boolean
        visibleToEmployer:
          description: will be visible to potential employers
          type: boolean
      type: object
    EducationIntervalItem_External:
      properties:
        abortedDate:
          description: aborted date
          examples:
            - '2020-02-28'
          format: date
          type: string
        endDate:
          description: end date
          examples:
            - '2020-02-28'
          format: date
          type: string
        startDate:
          description: start date
          examples:
            - '2020-01-31'
          format: date
          type: string
        statusCode:
          description: 'status code, codeset: TYÖNHAKUPROFIILI_KOULUTUS_TILA'
          type: string
      type: object
    EmploymentDto_External:
      properties:
        description:
          $ref: '#/components/schemas/DescriptionItem_External'
          description: employment item description
        employer:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          maxLength: 3
          type: object
        employerNameHidden:
          description: hide employer name
          type: boolean
        interval:
          $ref: '#/components/schemas/IntervalItem_External'
          description: employment interval
        title:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          maxLength: 3
          type: object
        useWithMatching:
          description: will be used in matching algorithms
          type: boolean
        visibleToEmployer:
          description: will be visible to potential employers
          type: boolean
      type: object
    EscoEntity_External:
      properties:
        altLabel:
          additionalProperties:
            items:
              type: string
            type: array
            uniqueItems: true
          readOnly: true
          type: object
        broader:
          items:
            type: string
          readOnly: true
          type: array
          uniqueItems: true
        description:
          additionalProperties:
            type: string
          readOnly: true
          type: object
        isEssentialSkillFor:
          items:
            type: string
          readOnly: true
          type: array
          uniqueItems: true
        isOptionalSkillFor:
          items:
            type: string
          readOnly: true
          type: array
          uniqueItems: true
        lastModified:
          format: date-time
          readOnly: true
          type: string
        narrower:
          items:
            $ref: '#/components/schemas/EscoEntity_External'
          readOnly: true
          type: array
          uniqueItems: true
        notation:
          readOnly: true
          type: string
        prefLabel:
          additionalProperties:
            type: string
          readOnly: true
          type: object
        relatedEssentialSkill:
          items:
            type: string
          readOnly: true
          type: array
          uniqueItems: true
        relatedOptionalSkill:
          items:
            type: string
          readOnly: true
          type: array
          uniqueItems: true
        skillReuseLevel:
          items:
            type: string
          readOnly: true
          type: array
          uniqueItems: true
        skillType:
          items:
            type: string
          readOnly: true
          type: array
          uniqueItems: true
        status:
          enum:
            - released
            - obsolete
            - blacklisted
          readOnly: true
          type: string
        uri:
          type: string
      type: object
    ExternalLinkDto_External:
      properties:
        label:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          type: object
        url:
          description: url
          examples:
            - https://nauruvirasto.fi/
          maxLength: 254
          minLength: 0
          pattern: ^(http|HTTP)[sS]?://[^/.\s]+\.[^\s]+$
          type: string
      type: object
    FullProfileDto_External:
      properties:
        businessActivities:
          items:
            $ref: '#/components/schemas/BusinessActivityDto_External'
          type: array
        certifications:
          $ref: '#/components/schemas/CertificationDto_External'
        drivingLicenses:
          $ref: '#/components/schemas/DrivingLicenseDto_External'
        educations:
          items:
            $ref: '#/components/schemas/EducationDto_External'
          type: array
        employments:
          items:
            $ref: '#/components/schemas/EmploymentDto_External'
          type: array
        experienceDescription:
          $ref: '#/components/schemas/DescriptionItem_External'
        externalLinks:
          items:
            $ref: '#/components/schemas/ExternalLinkDto_External'
          type: array
        generalInfo:
          $ref: '#/components/schemas/ProfileDto_External'
        jobPreferenceDescription:
          $ref: '#/components/schemas/DescriptionItem_External'
        languageSkills:
          items:
            $ref: '#/components/schemas/LanguageSkillDto_External'
          type: array
        projects:
          items:
            $ref: '#/components/schemas/ProjectDto_External'
          type: array
      type: object
    IntervalItem_External:
      properties:
        endDate:
          description: end date
          format: date
          pattern: yyyy-MM-dd
          type: string
        ongoing:
          description: ongoing, if true, end date must be null
          examples:
            - 'false'
          type: boolean
        startDate:
          description: start date, must be in the past
          format: date
          pattern: yyyy-MM-dd
          type: string
      type: object
    LanguageSkillDto_External:
      properties:
        code:
          description: 'language code, codeset: KIELI'
          type: string
        description:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          type: object
        level:
          description: 'language skill level, codeset: TYÖNHAKUPROFIILI_KIELITAIDON_TASO'
          type: string
      type: object
    ProfileDtoMeta_External:
      properties:
        created:
          description: created date
          format: date-time
          type: string
        externalId:
          description: external id
          format: uuid
          type: string
        lastModified:
          description: last modified date
          format: date-time
          type: string
        status:
          description: profile status (ACTIVE/PASSIVE)
          enum:
            - PASSIVE
            - ACTIVE
          type: string
        validTo:
          description: valid to date (when ACTIVE)
          format: date
          type: string
      type: object
    ProfileDto_External:
      properties:
        caption:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          type: object
        description:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          type: object
        meta:
          $ref: '#/components/schemas/ProfileDtoMeta_External'
          description: profile metadata
          readOnly: true
        personAvailability:
          description: 'availability, codeset: TYÖN_ALOITUS'
          type: string
        personAvailabilityText:
          additionalProperties:
            type: string
          description: 'availability freetext for ''according to agreement'' - keys:
            languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          type: object
        preferredCountries:
          description: 'preferred countries, codeset: MAA'
          items:
            type: string
          maxItems: 120
          maxLength: 120
          minItems: 0
          type: array
        preferredMunicipalities:
          description: 'preferred municipalities (Finland), codeset: KUNTA'
          items:
            type: string
          maxItems: 120
          maxLength: 120
          minItems: 0
          type: array
        preferredRegions:
          description: 'preferred regions (Finland), codeset: MAAKUNTA'
          items:
            type: string
          maxItems: 120
          maxLength: 120
          minItems: 0
          type: array
        startDate:
          description: availability start date
          format: date
          type: string
        willingToTravel:
          description: willingness to travel
          type: boolean
        willingToWorkRemotely:
          description: willingness to work remotely
          type: boolean
      type: object
    ProjectDto_External:
      properties:
        description:
          $ref: '#/components/schemas/DescriptionItem_External'
          description: freetext description
        interval:
          $ref: '#/components/schemas/IntervalItem_External'
          description: interval
        title:
          additionalProperties:
            type: string
          description: 'keys: languages (fi,sv,en), values: localized descriptions'
          examples:
            - '{"fi": "suomeksi", "sv": "på svenska", "en": "in english"}'
          type: object
        useWithMatching:
          description: will be used in matching algorithms
          type: boolean
        visibleToEmployer:
          description: will be visible to potential employers
          type: boolean
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  contact:
    name: "KEHA-keskus"
  description: Profile Service that will expose rest endpoints to store and query
    information of profiles
  title: TMT Profile Service
  version: v1
openapi: 3.1.0
paths:
  /v1/profile:
    get:
      description: get profile information
      operationId: getProfile
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullProfileDto_External'
          description: OK
      tags:
        - external-manage
    put:
      description: put profile information
      operationId: putProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FullProfileDto_External'
        required: true
      responses:
        '204':
          description: Successful operation
      tags:
        - external-manage
servers:
  - description: Local development environment
    url: http://localhost:8540
tags:
  - name: external-manage
  - name: tmt-denounce
  - name: tmt-matching
  - name: tmt-manage
  - name: tmt-user
  - name: internal-kafka
  - name: internal-atmt-matching
  - name: internal-profile
