services:
  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./scripts/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: yksilo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    labels:
      org.springframework.boot.jdbc.parameters: 'user=yksilo&password=yksilo'

  tmt-mock-api:
    profiles:
      - "mock"
    build:
      context: ./tmt-mock
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8580:8080"

  tmt-osaamissuosittelija-api:
    build:
      dockerfile: Dockerfile.osaamissuosittelija
    ports:
      - "127.0.0.1:8680:8080"

volumes:
  data:
