#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<'EOSQL'
    CREATE ROLE yksilo WITH LOGIN PASSWORD 'yksilo';
    GRANT CONNECT,CREATE,TEMPORARY ON DATABASE yksilo TO yksilo;
    CREATE ROLE dataloader WITH LOGIN PASSWORD 'dataloader';
    GRANT CONNECT,TEMPORARY ON DATABASE yksilo TO dataloader;
    CREATE ROLE rds_iam;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "yksilo" <<'EOSQL'
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE SCHEMA aws_s3; -- Placeholder schema for AWS S3 integration
EOSQL

# migrations generated by script (read from .psql file to avoid Docker entrypoint auto-execution)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "yksilo" -f "$SCRIPT_DIR/yksilo-migrations.psql"
