jod:
  external-api:
    apiKey: "test-${random.uuid}"

logging:
  level:
    sql: DEBUG
    fi.okm.jod: DEBUG

management:
  defaults:
    metrics:
      export:
        enabled: false
  simple:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,metrics"

spring:
  cloud:
    aws:
      sqs:
        enabled: false
