jod:
  external-api:
    apiKey: "test-${random.uuid}"
  cv:
    request-queue: http://localhost:8430

logging:
  level:
    sql: DEBUG
    fi.okm.jod: DEBUG

management:
  defaults:
    metrics:
      export:
        enabled: false
  simple:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

spring:
  cloud:
    aws:
      sqs:
        enabled: false
