---
spring:
  ssl:
    bundle:
      pem:
        koski-ssl-bundle:
          keystore:
            certificate: "${jod.koski.client-cert:../koski/koski-luovutuspalvelu/proxy/test/testca/certs/client.crt}"
            private-key: "${jod.koski.client-key:../koski/koski-luovutuspalvelu/proxy/test/testca/private/client.key}"
          truststore:
            # Our client will trust the Authorization and Resource server with it's the certificate.
            certificate: "${jod.koski.server-cert:../koski/koski-luovutuspalvelu/proxy/test/testca/certs/root-ca.crt}"
  security:
    oauth2:
      client:
        registration:
          koski:
            provider: koski-mtls
            client-id: "${jod.oauth2.koski.client-id:omadataoauth2sample}"
            client-authentication-method: none
            authorization-grant-type: authorization_code
            scope: HENKILOTIEDOT_HETU,OPISKELUOIKEUDET_KAIKKI_TIEDOT
            client-name: koski
            redirect-uri: "{baseUrl}/oauth2/response/{registrationId}"
        provider:
          koski-mtls:
            token-uri: "${jod.oauth2.koski.provider.token-uri:https://localhost:7022/koski/api/omadata-oauth2/authorization-server}"
            authorization-uri: "${jod.oauth2.koski.provider.authorization-uri:http://localhost:7021/koski/omadata-oauth2/authorize}"

jod:
  koski:
    resource-server:
      url: "${jod.oauth2.koski.resource-server.url:https://localhost:7022/koski/api/omadata-oauth2/resource-server}"
