---
jod:
  authentication: suomifi

spring:
  security:
    saml2:
      relyingparty:
        registration:
          jodsuomifi:
            name-id-format: "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
            singlelogout:
              url: "{baseUrl}/logout/saml2/slo/{registrationId}"
              response-url: "{baseUrl}/logout/saml2/slo/{registrationId}"
              binding: post
            signing:
              credentials:
                - private-key-location: "${jod.rp.key}"
                  certificate-location: "${jod.rp.crt}"
            decryption:
              credentials:
                - private-key-location: "${jod.rp.key}"
                  certificate-location: "${jod.rp.crt}"
            assertingparty:
              metadata-uri: "https://static.apro.tunnistus.fi/static/metadata/idp-metadata.xml"
              singlesignon:
                binding: "REDIRECT"
                url: "https://testi.apro.tunnistus.fi/idp/profile/SAML2/Redirect/SSO"
              singlelogout:
                binding: "REDIRECT"
                url: "https://testi.apro.tunnistus.fi/idp/profile/SAML2/Redirect/SLO"
                response-url: "https://testi.apro.tunnistus.fi/idp/profile/SAML2/Redirect/SLO"

server:
  servlet:
    session:
      cookie:
        same-site: none
