-- OPHJOD-2731: Add koulutuskoodi
CREATE TABLE koulutuskoodi (
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  koodi VARCHAR(255)                            NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

CREATE TABLE koulutuskoodi_kaannos (
  koulutuskoodi_id BIGINT       NOT NULL REFERENCES koulutuskoodi (id),
  kaannos_key      VARCHAR(255) NOT NULL CHECK (kaannos_key IN ('FI', 'SV', 'EN')),
  nimi             TEXT         NOT NULL,
  kuvaus           TEXT,
  PRIMARY KEY (koulutuskoodi_id, kaannos_key)
);
