CREATE TABLE koski_tehtava
(
  id        UUID        NOT NULL PRIMARY KEY,
  yksilo_id UUID        NOT NULL REFERENCES yksilo (id) ON DELETE CASCADE,
  tila      VARCHAR(20) NOT NULL DEFAULT 'VALMIS' CHECK ( tila IN ('VALMIS', 'EPAONNISTUNUT', 'POISTETTU') ),
  tulos     JSONB,
  luotu     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  muokattu  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ON koski_tehtava (yksilo_id);
